In [2]:
my_list=[1,2,3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0, 10) # gen array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2) # with step size

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5)) # tuple - number of rows, columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,5,10) # one dimensional vector from 0 to 5 with 10 evenly divided points

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.random.rand(5)

array([0.52975836, 0.20680684, 0.0496981 , 0.45395525, 0.06041254])

In [20]:
np.random.rand(5,5)

array([[0.12483724, 0.70947687, 0.00100215, 0.09416966, 0.73063438],
       [0.19284773, 0.23644841, 0.84643705, 0.55069179, 0.48437402],
       [0.43775978, 0.53145232, 0.8809161 , 0.64865908, 0.05851834],
       [0.44256737, 0.560579  , 0.32573777, 0.21346   , 0.36015486],
       [0.69951923, 0.80770553, 0.92962755, 0.04958409, 0.33336245]])

In [21]:
np.random.randint(5)

4

In [22]:
np.radom.randn(2)

AttributeError: module 'numpy' has no attribute 'radom'

In [23]:
np.random.randn(2)

array([-1.06387626,  0.79573642])

In [24]:
np.random.rand(4,4)

array([[0.99947242, 0.89481483, 0.37147152, 0.549396  ],
       [0.95424824, 0.3554082 , 0.52173995, 0.88403766],
       [0.99246082, 0.12919906, 0.87820446, 0.27960343],
       [0.68395044, 0.16272549, 0.37356687, 0.25033698]])

In [25]:
arr = np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([13, 12, 25, 13, 15, 37,  5, 42, 43, 15])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr.reshape(2,5)

array([[13, 12, 25, 13, 15],
       [37,  5, 42, 43, 15]])

In [31]:
ranarr.max()

43

In [32]:
ranarr.min()

5

In [33]:
ranarr.argmax()

8

In [34]:
ranarr

array([13, 12, 25, 13, 15, 37,  5, 42, 43, 15])

In [35]:
ranarr.argmin()

6

In [36]:
ranarr.min()

5

In [37]:
arr.shape()

TypeError: 'tuple' object is not callable

In [38]:
arr.shape

(25,)

In [39]:
arr = arr.reshape(5,5)

In [40]:
arr.shape

(5, 5)

In [41]:
arr.dtype

dtype('int32')

In [42]:
from numpy.random import randint as ran

In [43]:
ran(4)

0

In [44]:
 arr = np.aranage(0,11)

AttributeError: module 'numpy' has no attribute 'aranage'

In [45]:
import numpy as np

In [46]:
arr = np.arange(0, 11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [51]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [52]:
1/0

ZeroDivisionError: division by zero

In [53]:
arr / arr

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [54]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [56]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [57]:
np.max(arr)

10

In [58]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [59]:
np.log(arr)

E:\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])